# Artificial Neural Network

### Importing the libraries

In [16]:
import numpy as np
import pandas as pd
import tensorflow as tf
import keras

In [2]:
tf.__version__

'2.13.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [8]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:,:-1].values  #features
y = dataset.iloc[:,-1].values  #dependent variable

### Splitting the dataset into the Training set and Test set

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [12]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


###  Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [18]:
ann = tf.keras.models.Sequential()  #o Sequencial cria uma ann inicializada como uma sequencia de layers

### Adding the input layer and the first hidden layer

In [20]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))   #units são os hidden neurons

### Adding the second hidden layer

In [22]:
ann.add(tf.keras.layers.Dense(units =6 , activation = 'relu'))

### Adding the output layer

In [23]:
ann.add(tf.keras.layers.Dense(units = 1)) #activation is None como default, e usamos esta pois estamos perante uma regressão que os valores são contínuos
#se fosse um valor binário usavamos a ativação sigmoid

## Part 3 - Training the ANN

### Compiling the ANN

In [35]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error', metrics = ['accuracy'])
#na regressão a loss é sempre mean_squared_error, a soma dos quadrados

### Training the ANN model on the Training set

In [36]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 [==============================] - 1s 2ms/step - loss: 27.0872 - accuracy: 0.0000e+00
Epoch 2/100
240/240 [==============================] - 0s 2ms/step - loss: 26.9161 - accuracy: 0.0000e+00
Epoch 3/100
240/240 [==============================] - 0s 2ms/step - loss: 26.5766 - accuracy: 0.0000e+00
Epoch 4/100
240/240 [==============================] - 0s 2ms/step - loss: 26.9028 - accuracy: 0.0000e+00
Epoch 5/100
240/240 [==============================] - 0s 2ms/step - loss: 27.6577 - accuracy: 0.0000e+00
Epoch 6/100
240/240 [==============================] - 0s 2ms/step - loss: 26.6800 - accuracy: 0.0000e+00
Epoch 7/100
240/240 [==============================] - 0s 2ms/step - loss: 27.3857 - accuracy: 0.0000e+00
Epoch 8/100
240/240 [==============================] - 0s 2ms/step - loss: 27.1305 - accuracy: 0.0000e+00
Epoch 9/100
240/240 [==============================] - 0s 2ms/step - loss: 27.3105 - accuracy: 0.0000e+00
Epoch 10/100
240/240 [========================

### Predicting the results of the Test set

In [42]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)  #colocar apenas duas casas decimais
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)),1 )) #colocar va vertical o y_test

60/60 [==============================] - 0s 2ms/step
[[455.2  458.96]
 [464.23 463.29]
 [439.6  435.27]
 ...
 [479.22 476.22]
 [425.34 440.29]
 [466.56 467.92]]
